name: Java CI 

on:
  push:
    branches: [ "ชาซีลอนปั่นหวานน้อยใส่ช้อกชิพ" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref}}
        fetch-depth: ${{ env.PR_FETCH_DEPTH}}
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Compile Java
      run: |
        cd ชาซีลอนปั่นหวานน้อยใส่ช้อกชิพ/HolidayTravelvehicle/
        javac -d . *.java 
    - shell: bash
      run: | 
        cd ชาซีลอนปั่นหวานน้อยใส่ช้อกชิพ/HolidayTravelvehicle/
        java Main >> output.log
    - name: Upload output_main result 
      uses: actions/upload-artifact@v4
      with:
           name: output
           path: ชาซีลอนปั่นหวานน้อยใส่ช้อกชิพ/HolidayTravelvehicle/output.log

           
    - name: Display Output
      shell: bash
      run: |
          value=$(cat $GITHUB_WORKSPACE/ชาซีลอนปั่นหวานน้อยใส่ช้อกชิพ/HolidayTravelvehicle/output.log)
          echo "The result is $value"
